version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: ["dependencies"]
    groups:
      github-actions-ci:
        patterns: ["*"]
  - package-ecosystem: pip
    directory: "/backend"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: ["dependencies"]
    groups:
      pip-be:
        patterns: ["*"]
  - package-ecosystem: npm
    cooldown:
      default-days: 14
    directory: "/frontend"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: ["dependencies"]
    groups:
      npm-fe:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: "/backend"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: ["dependencies"]
    groups:
      docker-be:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: "/frontend"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: ["dependencies"]
    groups:
      docker-fe:
        patterns: ["*"]
